### ISSUE TITLE
求适配类原生

### ISSUE THREAD

**Issue by Alittfre** [Xposed-Modules-Repo/com.gswxxn.restoresplashscreen#2]
尝试在类原生上使用，功能看起来都正常，但是lsp日志有报错，希望可以减少报错。
以下是报错日志：
[ 2022-07-12T22:44:32.617    10163:  2742:  2939 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: Can't find this Method --> name:[isStaringWindowUnderNightMode] paramCount:[0] paramTypes:[()] returnType:[unspecified] modifiers:[] in Class [class android.window.SplashScreenView$Builder] by YukiHookAPI#ReflectionTool
 at s.a.c(Unknown Source:1352)
 at p.c.y(Unknown Source:28)
 at p.c.v(Unknown Source:14)
 at j.d.o(Unknown Source:678)
 at t.a.n(Unknown Source:3)
 at w.b.l(Unknown Source:0)
 at w.b.k(Unknown Source:30)
 at j.b$a.a(Unknown Source:12)
 at j.b$a.g(Unknown Source:2)
 at m.a.c(Unknown Source:18)
 at e0.a.f(Unknown Source:101)
 at j.c.d(Unknown Source:73)
 at j.c.e(Unknown Source:16)
 at j.c.b(Unknown Source:27)
 at com.gswxxn.restoresplashscreen.hook.HookEntry_YukiHookXposedInit.handleLoadPackage(Unknown Source:2)
 at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
 at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
 at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
 at I.afterHookedMethod(Unknown Source:1)
 at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
 at LSPHooker_.getClassLoader(Unknown Source:8)
 at android.app.LoadedApk.getResources(LoadedApk.java:1310)
 at android.app.ContextImpl.createAppContext(ContextImpl.java:3036)
 at android.app.ContextImpl.createAppContext(ContextImpl.java:3028)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6660)
 at android.app.ActivityThread.access$1500(ActivityThread.java:256)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7870)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[ 2022-07-12T22:44:32.618    10163:  2742:  2939 I/LSPosed-Bridge  ] [RestoreSplashScreen][E]--> [com.android.systemui] Hooked Member with a finding error by [class] android.window.SplashScreenView$Builder [throwable] null [instance] class android.window.SplashScreenView$Builder [Default]
[ 2022-07-12T22:44:32.618    10163:  2742:  2939 E/LSPosed-Bridge  ] java.lang.Throwable: Finding Error isSetUpMember [true] [Default]
 at o.b$b.r(Unknown Source:345)
 at o.b.h(Unknown Source:54)
 at o.b.a(Unknown Source:0)
 at o.a.run(Unknown Source:4)
 at java.lang.Thread.run(Thread.java:920)

**Comment by GSWXXN** [comment]
请提供一下刷机包的下载链接

**Comment by Alittfre** [comment]
> 请提供一下刷机包的下载链接

https://download.pixelexperience.org/changelog/polaris/PixelExperience_Plus_polaris-12.1-20220628-1736-OFFICIAL.zip/

**Comment by GSWXXN** [comment]
我拆包看了一下，根据你之前的描述 “忽略深色模式” 在你的设备上可以生效。但是这完全是不可能的事情啊，因为这个功能用到的函数`isStaringWindowUnderNightMode()`在你的设备上不存在，也就是说这个功能理论上开还是关效果是一样的，只不过开了之后会输出错误log。你有没有尝试过关闭这个开关看下在深色模式下的效果呢

**Comment by Alittfre** [comment]
> 我拆包看了一下，根据你之前的描述 “忽略深色模式” 在你的设备上可以生效。但是这完全是不可能的事情啊，因为这个功能用到的函数`isStaringWindowUnderNightMode()`在你的设备上不存在，也就是说这个功能理论上开还是关效果是一样的，只不过开了之后会输出错误log。你有没有尝试过关闭这个开关看下在深色模式下的效果呢

未开启忽略深色模式开关并切换系统深色模式的效果：
![Screenshot_20220801-070114_微信](https://user-images.githubusercontent.com/51853302/182049560-b8f79fdf-3206-4d9e-822f-e85d08adfc10.png)
![Screenshot_20220801-070129_微信](https://user-images.githubusercontent.com/51853302/182049563-10a74aaa-a647-4506-8301-ab9135b86f14.png)
开启忽略深色模式开关并切换系统深色模式的效果：
![Screenshot_20220801-070216_微信](https://user-images.githubusercontent.com/51853302/182049590-55a882b5-002d-4791-9fdb-535a57acb548.png)
![Screenshot_20220801-070235_微信](https://user-images.githubusercontent.com/51853302/182049593-41efdb91-92f0-445d-a70d-88deac010c0d.png)

**Comment by GSWXXN** [comment]
好了，我大概明白是怎么回事了，`isStaringWindowUnderNightMode()`函数似乎是 MIUI 加上的
在 MIUI 上需要干预这个函数返回值再设置背景颜色才能做到 "忽略深色模式"

在你的系统里不需要干预任何函数结果，直接设置 Splash Screen 背景颜色就可以了

在下个版本里我加个系统名称判断就可以了

**Comment by Alittfre** [comment]
> 好了，我大概明白是怎么回事了，`isStaringWindowUnderNightMode()`函数似乎是 MIUI 加上的 在 MIUI 上需要干预这个函数返回值再设置背景颜色才能做到 "忽略深色模式"
> 
> 在你的系统里不需要干预任何函数结果，直接设置 Splash Screen 背景颜色就可以了
> 
> 在下个版本里我加个系统名称判断就可以了

好的
